<a href="https://colab.research.google.com/github/EzeGB/PythonExcercises/blob/panditas/Pandas_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.DataFrame(data = [[61,70,55],
                          [48,42,75],
                          [15,75,58],
                          [35,40,22]],
                  columns = ['Primer parcial','Segundo parcial','Tercer parcial']
                  )
df.head(2)

   Primer parcial  Segundo parcial  Tercer parcial
0              61               70              55
1              48               42              75

In [4]:
df.tail(3)

   Primer parcial  Segundo parcial  Tercer parcial
1              48               42              75
2              15               75              58
3              35               40              22

##Exercise
Add 7 rows to the dataFrame

In [5]:
df = pd.DataFrame(data = [[61,70,55],
                          [48,42,75],
                          [15,75,58],
                          [35,40,22],
                          #------------#
                          [100,100,100],
                          [1,1,1],
                          [51,51,51],
                          [70,70,70],
                          [51,100,70],
                          [28,100,45],
                          [68,89,49]],
                  columns = ['Primer parcial','Segundo parcial','Tercer parcial']
                  )

In [7]:
df_1p = df['Primer parcial']
df_1p

0      61
1      48
2      15
3      35
4     100
5       1
6      51
7      70
8      51
9      28
10     68
Name: Primer parcial, dtype: int64

In [9]:
df_prim_seg_mt = df[['Primer parcial','Segundo parcial']]
df_prim_seg_mt.head(5)

   Primer parcial  Segundo parcial
0              61               70
1              48               42
2              15               75
3              35               40
4             100              100

In [11]:
df_prim_seg_mt.to_csv('Primer y segundo parcial.csv',index=False)

In [12]:
df_employees = pd.read_csv('empleadosCSV.csv')
df_employees.head(10)

,id,nombre,apellido,sexo,fecha_nacimiento,fecha_incorporacion,fecha_salida,salario_base
0,1,Juan,Pérez,M,1985-03-15,2015-06-01,NaN,4500.0
1,2,María,González,F,1990-07-22,2018-03-15,NaN,5200.0
2,3,Carlos,Rodríguez,M,1988-11-30,2016-09-01,NaN,4800.0
3,4,Ana,Martínez,M,1992-05-10,2019-01-20,NaN,4100.0
4,5,Luis,López,M,1987-09-05,2014-11-15,2023-08-30,5500.0
5,6,Carmen,Sánchez,F,1991-02-28,2017-04-10,NaN,4900.0
6,7,Pedro,Ramírez,M,2018-12-18,2013-07-25,NaN,5800.0
7,8,Laura,Torres,M,15/08/1993,2020-02-14,NaN,3800.0
8,9,Diego,Flores,M,1989-04-25,2016-12-01,NaN,4700.0
9,10,Sofia,Rivera,F,1994-10-12,2021-05-18,NaN,3500.0

In [13]:
df_employees.columns

Index(['id', 'nombre', 'apellido', 'sexo', 'fecha_nacimiento',
       'fecha_incorporacion', 'fecha_salida', 'salario_base'],
      dtype='object')

In [14]:
df_employees.dtypes

id                       int64
nombre                  object
apellido                object
sexo                    object
fecha_nacimiento        object
fecha_incorporacion     object
fecha_salida            object
salario_base           float64
dtype: object

In [15]:
df_employees[['nombre','apellido']].head(5)

   nombre   apellido
0    Juan      Pérez
1   María   González
2  Carlos  Rodríguez
3     Ana   Martínez
4    Luis      López