<a href="https://colab.research.google.com/github/EzeGB/PythonExcercises/blob/pandazosact/Pandas_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame(data = [[61,70,55],
                          [48,42,75],
                          [15,75,58],
                          [35,40,22]],
                  columns = ['Primer parcial','Segundo parcial','Tercer parcial']
                  )
df.head(2)

   Primer parcial  Segundo parcial  Tercer parcial
0              61               70              55
1              48               42              75

In [3]:
df.tail(3)

   Primer parcial  Segundo parcial  Tercer parcial
1              48               42              75
2              15               75              58
3              35               40              22

##Exercise
Add 7 rows to the dataFrame

In [4]:
df = pd.DataFrame(data = [[61,70,55],
                          [48,42,75],
                          [15,75,58],
                          [35,40,22],
                          #------------#
                          [100,100,100],
                          [1,1,1],
                          [51,51,51],
                          [70,70,70],
                          [51,100,70],
                          [28,100,45],
                          [68,89,49]],
                  columns = ['Primer parcial','Segundo parcial','Tercer parcial']
                  )

In [5]:
df_1p = df['Primer parcial']
df_1p

0      61
1      48
2      15
3      35
4     100
5       1
6      51
7      70
8      51
9      28
10     68
Name: Primer parcial, dtype: int64

In [6]:
df_prim_seg_mt = df[['Primer parcial','Segundo parcial']]
df_prim_seg_mt.head(5)

   Primer parcial  Segundo parcial
0              61               70
1              48               42
2              15               75
3              35               40
4             100              100

In [7]:
df_prim_seg_mt.to_csv('Primer y segundo parcial.csv',index=False)

In [25]:
df_employees = pd.read_csv('empleadosCSV.csv')
df_employees.head(30)

,id,nombre,apellido,sexo,fecha_nacimiento,fecha_incorporacion,fecha_salida,salario_base
0,1,Juan,Pérez,M,1985-03-15,2015-06-01,NaN,4500.0
1,2,María,González,F,1990-07-22,2018-03-15,NaN,5200.0
2,3,Carlos,Rodríguez,M,1988-11-30,2016-09-01,NaN,4800.0
3,4,Ana,Martínez,M,1992-05-10,2019-01-20,NaN,4100.0
4,5,Luis,López,M,1987-09-05,2014-11-15,2023-08-30,5500.0
5,6,Carmen,Sánchez,F,1991-02-28,2017-04-10,NaN,4900.0
6,7,Pedro,Ramírez,M,2018-12-18,2013-07-25,NaN,5800.0
7,8,Laura,Torres,M,15/08/1993,2020-02-14,NaN,3800.0
8,9,Diego,Flores,M,1989-04-25,2016-12-01,NaN,4700.0
9,10,Sofia,Rivera,F,1994-10-12,2021-05-18,NaN,3500.0
10,11,Miguel,Gómez,M,1984-06-08,2012-03-20,2022-12-15,6200.0
11,12,Valentina,Díaz,NaN,1995-01-30,2022-08-01,NaN,3300.0
12,13,Andrés,Morales,M,1990-08-14,2017-10-05,NaN,4600.0
13,14,Isabella,Jiménez,F,1993-03-22,2019-07-12,NaN,4200.0
14,15,Roberto,Hernández,M,1986-11-07,2015-02-28,NaN,5100.0
15,16,Camila,Castro,M,1991-09-19,2018-06-20,NaN,4400.0
16,17,Fernando,Ortiz,M,1988-02-11,2016-04-15,NaN,4950.0
17,18,Daniela,Núñez,F,NaN,2020-09-10,NaN,3900.0
18,19,Javier,Vargas,M,1987-07-26,2014-12-03,NaN,5400.0
19,20,Gabriela,Rojas,F,2015-12-05,2019-03-25,NaN,4300.0
20,21,Ricardo,Medina,M,1985-10-20,2013-08-17,2021-06-30,5900.0
21,22,Paula,Guzmán,F,1994-04-15,2021-11-08,NaN,3600.0
22,23,Alejandro,Silva,M,1989-06-30,2017-01-22,NaN,4850.0
23,24,Natalia,Mendoza,F,1991-11-28,2018-08-05,NaN,4550.0
24,25,Sebastián,Paredes,M,1986-03-12,2014-05-30,NaN,5600.0
25,26,Carolina,Reyes,F,1993-08-09,2020-01-15,NaN,4000.0
26,27,Martín,Vega,M,1988-01-17,2016-07-20,NaN,4750.0
27,28,Lucía,Romero,M,1990-05-23,2017-11-12,NaN,4650.0
28,29,Gonzalo,Muñoz,M,1987-09-08,2015-03-18,NaN,5250.0
29,30,Renata,Aguilar,F,1992-02-14,2019-06-28,NaN,4150.0

In [10]:
df_employees.columns

Index(['id', 'nombre', 'apellido', 'sexo', 'fecha_nacimiento',
       'fecha_incorporacion', 'fecha_salida', 'salario_base'],
      dtype='object')

In [ ]:
df_employees.dtypes

id                       int64
nombre                  object
apellido                object
sexo                    object
fecha_nacimiento        object
fecha_incorporacion     object
fecha_salida            object
salario_base           float64
dtype: object

In [11]:
df_employees[['nombre','apellido']].head(5)

   nombre   apellido
0    Juan      Pérez
1   María   González
2  Carlos  Rodríguez
3     Ana   Martínez
4    Luis      López

##Exercise
Get the empleadoCSV registers, where the sex is F and salary is between 4000 and 6000(inclusive)

In [17]:
df_filter = df_employees [(df_employees['sexo']=='F') & (df_employees['salario_base'] >= 4000) & (df_employees['salario_base'] <= 6000)]
df_filter[['nombre','apellido']].head(10)

      nombre  apellido
1      María  González
5     Carmen   Sánchez
13  Isabella   Jiménez
19  Gabriela     Rojas
23   Natalia   Mendoza
25  Carolina     Reyes
29    Renata   Aguilar
33   Adriana   Estrada
37   Mariana      León
39     Elena      Peña

In [20]:
df_employees['sexo'] = df_employees['sexo'].fillna('No consignado')
df_employees.head(20)

,id,nombre,apellido,sexo,fecha_nacimiento,fecha_incorporacion,fecha_salida,salario_base
0,1,Juan,Pérez,M,1985-03-15,2015-06-01,NaN,4500.0
1,2,María,González,F,1990-07-22,2018-03-15,NaN,5200.0
2,3,Carlos,Rodríguez,M,1988-11-30,2016-09-01,NaN,4800.0
3,4,Ana,Martínez,M,1992-05-10,2019-01-20,NaN,4100.0
4,5,Luis,López,M,1987-09-05,2014-11-15,2023-08-30,5500.0
5,6,Carmen,Sánchez,F,1991-02-28,2017-04-10,NaN,4900.0
6,7,Pedro,Ramírez,M,2018-12-18,2013-07-25,NaN,5800.0
7,8,Laura,Torres,M,15/08/1993,2020-02-14,NaN,3800.0
8,9,Diego,Flores,M,1989-04-25,2016-12-01,NaN,4700.0
9,10,Sofia,Rivera,F,1994-10-12,2021-05-18,NaN,3500.0
10,11,Miguel,Gómez,M,1984-06-08,2012-03-20,2022-12-15,6200.0
11,12,Valentina,Díaz,No consigando,1995-01-30,2022-08-01,NaN,3300.0
12,13,Andrés,Morales,M,1990-08-14,2017-10-05,NaN,4600.0
13,14,Isabella,Jiménez,F,1993-03-22,2019-07-12,NaN,4200.0
14,15,Roberto,Hernández,M,1986-11-07,2015-02-28,NaN,5100.0
15,16,Camila,Castro,M,1991-09-19,2018-06-20,NaN,4400.0
16,17,Fernando,Ortiz,M,1988-02-11,2016-04-15,NaN,4950.0
17,18,Daniela,Núñez,F,NaN,2020-09-10,NaN,3900.0
18,19,Javier,Vargas,M,1987-07-26,2014-12-03,NaN,5400.0
19,20,Gabriela,Rojas,F,2015-12-05,2019-03-25,NaN,4300.0

In [21]:
df_employees['salario_base'].mean()

np.float64(4698.989898989899)

##exercise
1. impute values in column salario_base with 0
2. impute values in column salario_base with the mean

In [28]:
df_employees0 = pd.read_csv('empleadosCSV.csv')
df_employeesM = pd.read_csv('empleadosCSV.csv')

df_employees0['salario_base'] = df_employees0['salario_base'].fillna(0)
df_employeesM['salario_base'] = df_employeesM['salario_base'].fillna(df_employees['salario_base'].mean())

df_employees0.head(20)

,id,nombre,apellido,sexo,fecha_nacimiento,fecha_incorporacion,fecha_salida,salario_base
0,1,Juan,Pérez,M,1985-03-15,2015-06-01,NaN,4500.0
1,2,María,González,F,1990-07-22,2018-03-15,NaN,5200.0
2,3,Carlos,Rodríguez,M,1988-11-30,2016-09-01,NaN,4800.0
3,4,Ana,Martínez,M,1992-05-10,2019-01-20,NaN,4100.0
4,5,Luis,López,M,1987-09-05,2014-11-15,2023-08-30,5500.0
5,6,Carmen,Sánchez,F,1991-02-28,2017-04-10,NaN,4900.0
6,7,Pedro,Ramírez,M,2018-12-18,2013-07-25,NaN,5800.0
7,8,Laura,Torres,M,15/08/1993,2020-02-14,NaN,3800.0
8,9,Diego,Flores,M,1989-04-25,2016-12-01,NaN,4700.0
9,10,Sofia,Rivera,F,1994-10-12,2021-05-18,NaN,3500.0
10,11,Miguel,Gómez,M,1984-06-08,2012-03-20,2022-12-15,6200.0
11,12,Valentina,Díaz,NaN,1995-01-30,2022-08-01,NaN,3300.0
12,13,Andrés,Morales,M,1990-08-14,2017-10-05,NaN,4600.0
13,14,Isabella,Jiménez,F,1993-03-22,2019-07-12,NaN,4200.0
14,15,Roberto,Hernández,M,1986-11-07,2015-02-28,NaN,5100.0
15,16,Camila,Castro,M,1991-09-19,2018-06-20,NaN,4400.0
16,17,Fernando,Ortiz,M,1988-02-11,2016-04-15,NaN,4950.0
17,18,Daniela,Núñez,F,NaN,2020-09-10,NaN,3900.0
18,19,Javier,Vargas,M,1987-07-26,2014-12-03,NaN,5400.0
19,20,Gabriela,Rojas,F,2015-12-05,2019-03-25,NaN,4300.0

In [29]:
df_employeesM.head(20)

,id,nombre,apellido,sexo,fecha_nacimiento,fecha_incorporacion,fecha_salida,salario_base
0,1,Juan,Pérez,M,1985-03-15,2015-06-01,NaN,4500.0
1,2,María,González,F,1990-07-22,2018-03-15,NaN,5200.0
2,3,Carlos,Rodríguez,M,1988-11-30,2016-09-01,NaN,4800.0
3,4,Ana,Martínez,M,1992-05-10,2019-01-20,NaN,4100.0
4,5,Luis,López,M,1987-09-05,2014-11-15,2023-08-30,5500.0
5,6,Carmen,Sánchez,F,1991-02-28,2017-04-10,NaN,4900.0
6,7,Pedro,Ramírez,M,2018-12-18,2013-07-25,NaN,5800.0
7,8,Laura,Torres,M,15/08/1993,2020-02-14,NaN,3800.0
8,9,Diego,Flores,M,1989-04-25,2016-12-01,NaN,4700.0
9,10,Sofia,Rivera,F,1994-10-12,2021-05-18,NaN,3500.0
10,11,Miguel,Gómez,M,1984-06-08,2012-03-20,2022-12-15,6200.0
11,12,Valentina,Díaz,NaN,1995-01-30,2022-08-01,NaN,3300.0
12,13,Andrés,Morales,M,1990-08-14,2017-10-05,NaN,4600.0
13,14,Isabella,Jiménez,F,1993-03-22,2019-07-12,NaN,4200.0
14,15,Roberto,Hernández,M,1986-11-07,2015-02-28,NaN,5100.0
15,16,Camila,Castro,M,1991-09-19,2018-06-20,NaN,4400.0
16,17,Fernando,Ortiz,M,1988-02-11,2016-04-15,NaN,4950.0
17,18,Daniela,Núñez,F,NaN,2020-09-10,NaN,3900.0
18,19,Javier,Vargas,M,1987-07-26,2014-12-03,NaN,5400.0
19,20,Gabriela,Rojas,F,2015-12-05,2019-03-25,NaN,4300.0

In [30]:
df_position = pd.DataFrame(data=[[1,'accountant'],
                                 [3,'administrator'],
                                 [15,'manager'],
                                 [86,'secretary'],
                                 [100,'human resources']],
                           columns = ['empleado','cargo'])
df_position

   empleado            cargo
0         1       accountant
1         3    administrator
2        15          manager
3        86        secretary
4       100  human resources

##MERGE as SQL join equivalent

In [32]:
df_join = pd.merge(df_employees,df_position, left_on = ['id'], right_on= ['empleado'])
df_join[['nombre','apellido','salario_base','cargo']]

      nombre    apellido  salario_base            cargo
0       Juan       Pérez        4500.0       accountant
1     Carlos   Rodríguez        4800.0    administrator
2    Roberto   Hernández        5100.0          manager
3    Yessica     Urrutia        4350.0        secretary
4  Constanza  Norambuena           NaN  human resources

Assign jobs to 5 more employees

In [34]:
df_position2 = pd.DataFrame(data=[[1,'accountant'],
                                 [3,'administrator'],
                                 [15,'manager'],
                                 [86,'secretary'],
                                 [100,'human resources'],
                                 [2,'marketing'],
                                 [19,'janitor'],
                                 [31,'finances'],
                                 [97,'director'],
                                 [99,'jury']],
                           columns = ['empleado_id','cargo'])
df_position

   empleado            cargo
0         1       accountant
1         3    administrator
2        15          manager
3        86        secretary
4       100  human resources
5         2        marketing
6        19          janitor
7        31         finances
8        97         director
9        99             jury

In [38]:
df_join = pd.merge(df_employeesM,df_position2, how='left', left_on = ['id'], right_on= ['empleado_id'], indicator=True)
df_join[['nombre','apellido','salario_base','cargo','_merge']]

       nombre    apellido  salario_base            cargo     _merge
0        Juan       Pérez   4500.000000       accountant       both
1       María    González   5200.000000        marketing       both
2      Carlos   Rodríguez   4800.000000    administrator       both
3         Ana    Martínez   4100.000000              NaN  left_only
4        Luis       López   5500.000000              NaN  left_only
..        ...         ...           ...              ...        ...
95      Paola     Órdenes   3850.000000              NaN  left_only
96    Gustavo   Espíndola   4700.000000         director       both
97   Victoria       Olave   4550.000000              NaN  left_only
98   Bernardo      Quiroz   5200.000000             jury       both
99  Constanza  Norambuena   4698.989899  human resources       both

[100 rows x 5 columns]

## pick only those who dont have a job

In [41]:
df_refilter = df_join[df_join['_merge'] == 'left_only']
df_refilter

,id,nombre,apellido,sexo,fecha_nacimiento,fecha_incorporacion,fecha_salida,salario_base,empleado_id,cargo,_merge
3,4,Ana,Martínez,M,1992-05-10,2019-01-20,NaN,4100.0,NaN,NaN,left_only
4,5,Luis,López,M,1987-09-05,2014-11-15,2023-08-30,5500.0,NaN,NaN,left_only
5,6,Carmen,Sánchez,F,1991-02-28,2017-04-10,NaN,4900.0,NaN,NaN,left_only
6,7,Pedro,Ramírez,M,2018-12-18,2013-07-25,NaN,5800.0,NaN,NaN,left_only
7,8,Laura,Torres,M,15/08/1993,2020-02-14,NaN,3800.0,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...
92,93,Enrique,Yáñez,M,1989-03-14,2017-05-19,NaN,4950.0,NaN,NaN,left_only
93,94,Jazmín,Montes,M,1991-10-08,2018-11-30,NaN,4400.0,NaN,NaN,left_only
94,95,Ramón,Mena,M,1986-06-20,2014-07-25,NaN,5550.0,NaN,NaN,left_only
95,96,Paola,Órdenes,F,1993-09-23,2020-08-14,NaN,3850.0,NaN,NaN,left_only
97,98,Victoria,Olave,F,1990-07-07,2017-08-11,2025-01-15,4550.0,NaN,NaN,left_only